### ISSUE TITLE
Mapa >> Ajustar Zoom do Mapa

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/mapa-diadograffiti-theme#10]
Oi @matheusgimenez,

Precisamos ajustar o Zoom do Mapa inicial pra que ele mostre mais de SP ja que a grande maioria dos PINs serao em Sao Paulo:

![image](https://cloud.githubusercontent.com/assets/5949986/19871225/08430154-9f82-11e6-88f4-7081d62075a0.png)

Algo assim acho que ficaria perfeito:

![image](https://cloud.githubusercontent.com/assets/5949986/19871282/3a4b863a-9f82-11e6-8c13-4b166c96b2f0.png)

No entanto, uma solucao mais fina que isso seria o agregador de Pins, pra mostrar o numero de pins naquela regiao...

**Comment by matheusgimenez** [comment]
Feito. Está no DEV.

**Comment by LuwkasLima** [comment]
Ta otimo @matheusgimenez ! Aprovado!
