### ISSUE TITLE
Ajuda >> Largura da Janela Modal

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/mapa-diadograffiti-theme#11]
@matheusgimenez precisamos deixar a largura do modal de Ajuda mais flexivel com base na resolucao de tela, veja como esta hoje:

![image](https://cloud.githubusercontent.com/assets/5949986/23044994/552c5188-f468-11e6-9c44-26a4fb1cc7ab.png)

**Comment by matheusgimenez** [comment]
Aumentei o tamanho do modal e ja enviei pro DEV.

**Comment by LuwkasLima** [comment]
Perfeito!

**Comment by LuwkasLima** [comment]
Pode mandar pra Producao!
