### ISSUE TITLE
Galeria >> Galeria de Mídia

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/mapa-diadograffiti-theme#6]
Quando um PIN é selecionado pelo usuário, a seguinte tela é apresentada (vinda da lateral direita) e cobrindo o Filtro:

![image](https://cloud.githubusercontent.com/assets/5949986/15520666/15ca6da4-21cd-11e6-9774-2b807432d78b.png)
1. Por padrão, o mapa deve apresentar **o último ano de dados**.
2. O primeiro campo é na verdade um "botão" que apresenta os Anos selecionados e que leva a um lightbox que será explicado em outra issue
3. Foto em tamanho medio e apresentada com opção de se navegar pelas próximas fotos.
4. Com o mouse em cima, as opções abaixo aparecem:
5. ZOOM: Abre a foto em um Modal em tamanho maior;
6. Acervo Completo: Leva à página relacionada **ao Ano da foto em questão** (se for uma foto de 2014, leva ao site de 2014, se é de 2015 leva ao site de 2015, etc..)
7. Galeria em miniatura que vai se movendo com o navegar da imagens em tamanho médio (acima);
8. Informação sobre o Endereço do PIN
9. Informação sobre os Artistas relacionados ao PIN

Link para o PSD: https://drive.google.com/a/brasa.art.br/file/d/0B9gQpzPmhZFkaU0tQlMwdzl2U1k/view?usp=sharing

**Comment by matheusgimenez** [comment]
Feito. Está no DEV

**Comment by LuwkasLima** [comment]
@matheusgimenez seguem meus comentarios:

**1. Por padrão, o mapa deve apresentar o último ano de dados.**
Não está OK. Está apresentando o ultimo PIN cadastrados e não o último ANO de fato. Está explicado no Issue #7 

**2. O primeiro campo é na verdade um "botão" que apresenta os Anos selecionados e que leva a um lightbox que será explicado em outra issue**
Não está levando ao Modal (por escolha do @matheusgimenez e está tudo bem quanto a isso), no entanto não está funcionando como esperado. Está tudo explicado na Issu #7 

**3. Foto em tamanho medio e apresentada com opção de se navegar pelas próximas fotos.**

![image](https://cloud.githubusercontent.com/assets/5949986/17414708/0ea318d4-5a4c-11e6-9c04-6f540fde9146.png)

Podemos aumentar a altura da imagem principal (numero 1) e reduzir o tamanho das imagens da galeria (numero 2). Tente deixar a imagem principal mais Quadrada aumentando a altura dela, ok?

**4. Com o mouse em cima, as opções abaixo aparecem:**
_\- ZOOM: Abre a foto em um Modal em tamanho maior;_
PERFEITO!

_\- Acervo Completo: Leva à página relacionada ao Ano da foto em questão (se for uma foto de 2014, leva ao site de 2014, se é de 2015 leva ao site de 2015, etc..)_
Esse aqui não está funcionando. Precisamos ter um campo no PIN onde podemos colocar o LINK para a página do Homenageado do ANO. Assim, quando a pessoa clica em uma foto que pertence a um PIN de um determinado ano, ela é levada ao link que foi colocado no PIN.

**7. Galeria em miniatura que vai se movendo com o navegar da imagens em tamanho médio (acima);**
PERFEITO!

**8. Informação sobre o Endereço do PIN**
Perfeito! (acho que podemos diminuir um pouco a fonte somente)

**9. Informação sobre os Artistas relacionados ao PIN**
Os nomes dos artistas não está aparecendo. Print na Issue #7

**Comment by LuwkasLima** [comment]
1. Limitar o numero de anos que podem ser escolhidos (sugestao de 4 anos por vez):

![image](https://cloud.githubusercontent.com/assets/5949986/17606710/a6ffbbe2-5fe6-11e6-966a-0e572b71386d.png)

Exemplo: https://select2.github.io/examples.html#multiple-max

3 - Comentado no issue #7 

4 - Ja sera resolvido, criando-se o link automatico atraves do ano da foto (solucao que o @matheusgimenez ja pensou)
