### ISSUE TITLE
Galeria >> Escolha do ANO

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/mapa-diadograffiti-theme#7]
Assim que o usuario seleciona o botão do ANO:

![image](https://cloud.githubusercontent.com/assets/5949986/15520961/a6ef2030-21ce-11e6-8a9f-fcb8a4175a16.png)

Abre um lightbox como esse:

![image](https://cloud.githubusercontent.com/assets/5949986/15520943/8ac87ad2-21ce-11e6-94bd-856850bafe4a.png)
1. Endereço do PIN
2. Anos disponíveis nesse PIN

Link para o PSD: https://drive.google.com/a/brasa.art.br/file/d/0B9gQpzPmhZFkaU0tQlMwdzl2U1k/view?usp=sharing

**Comment by matheusgimenez** [comment]
Fiz sem o modal utilizando um cara chamado select2. 

Está no dev.

**Comment by matheusgimenez** [comment]
oops, fechei sem querer hehe

**Comment by LuwkasLima** [comment]
@matheusgimenez seguinte, uma das funcionalidades mais importantes do Mapa nao esta OK. Vou detalhar tudo abaixo pra voce entender:

**1 - Possibilidade de escolher diferentes ANOS:**

A ideia fundamental do Mapa é ter a possibilidade de ver uma parede em um endereço ter vários graffites em diferentes anos. Por isso é importânte poder escolher MAIS DE UM ano para ver as midias disponiveis.

Detalhes do teste:

A - Criei um PIN novo em um mesmo endereco com o mesmo nome mas diferentes artistas, fotos e ANO:

![image](https://cloud.githubusercontent.com/assets/5949986/17414179/0e052f68-5a4a-11e6-92ee-9f9d854c1ce6.png)

Obs.: 1 PIN eh de 2012 e outro de 2016

B - Quando clico no PIN ele me tras somente o ULTIMO ANO CADASTRADO:

![image](https://cloud.githubusercontent.com/assets/5949986/17414221/35536a4e-5a4a-11e6-959e-45704bef0243.png)

Tentei ver se conseguia selecionar mais de um ano la no box "Selecione o Ano" e so aparece o ultimo PIN cadastrado (2012):

![image](https://cloud.githubusercontent.com/assets/5949986/17414279/70b18fc6-5a4a-11e6-8af5-1acdd26f2298.png)

**RESULTADO ESPERADO**

O resultado esperado inicial era a da abertura do Modal com todos os anos dos PINs que estão no mesmo endereço.

**2 - Nome dos Artistas**

O nome dos artistas não aparece na tela, ficam incubertos pelas imagens:

![image](https://cloud.githubusercontent.com/assets/5949986/17414344/b204d4ce-5a4a-11e6-9c57-b982eb295ddb.png)

Obs.: Acho que talvez a fonte do endereço esteja muito grande...

**3 - Não temos a possibilidade de subir outros arquivos a não ser Fotos?**

Ficou acordado que poderiamos subir arquivos de foto e video no Mapa. No entanto, a galeria é somente de imagem. Como subimo videos?

![image](https://cloud.githubusercontent.com/assets/5949986/17414502/4d264104-5a4b-11e6-86ab-640bb54071bb.png)

Obs.: Pra que serve a area de texto do PIN se ela não é apresentada no mapa?

**Comment by matheusgimenez** [comment]
Sobre os anos:

Cada post é um ano, até ai tudo certo, porem, vc precisa fazer essa relação usando parent page do WP. Ou seja, o primeiro post cadastrado vai ser o pai e os outros serão filhos. Isso é feito da mesma forma de páginas, tem o menuzinho do lado direito no editor, etc.

2: de fato depende muito da resolução, aqui no meu note ta de boa, por exemplo. Pensei em colocar um scroll ali, ficaria ruim?

3: de fato não me liguei nisso. No meu proximo sprint vou resolver.

Sobre sua ultima observação: Pra nada de fato.

**Comment by LuwkasLima** [comment]
1 - Vixi, entendi... Eh usavel, mas nao acho que seja o ideal. Mas em fim, nao estamos agora em posicao de redefinir isso, se funciona vou aplicar e continuar o teste.

Fiz o teste e esta funcional. So penso que deviamos tirar o botao "Atualizar" dali e coloar ele do lado do BOX. Porque assim da espaco pra darmos mais altura pra imagem, o que acha?

![image](https://cloud.githubusercontent.com/assets/5949986/17422304/49c260e4-5a76-11e6-9aa8-b6f742d47183.png)

Obs.: Tem como identificar na imagem (de alguma forma) que aquela imagem eh do ano de 2016 ou 2012?

2 - Na real, o que eu faria era: Quando a pessoa clica no PIN que a janela do lado direito aparece, eu jogaria o rodape pra baixo e dai o scroll seria pra pagina toda. Faz sentido?

3 - Beleza, sim de fato Videos seria muito interessantes e devem abrir no Modal como na foto.

Se voce conseguir tirar a area de Descricao vai ficar top.

Ta muito bom @matheusgimenez de verdade, ficou muito mais fidedigno com o layout do que muito trampo anterior. E nao conseguimos nem te acompanhar direito. Ta muito bom...

**Comment by matheusgimenez** [comment]
Todos pontos feitos

**Comment by LuwkasLima** [comment]
1 - Quando clico no PIN ele me tras somente o ULTIMO ANO CADASTRADO:

Decidimos que sera incluido o ANO ao lado da palavra "Acervo Completo". Ex: **Acervo Completo - 2016**

![image](https://cloud.githubusercontent.com/assets/5949986/17606327/9c018592-5fe4-11e6-92c9-bc0225338eba.png)

2 - Aumentar a imagem de cima pra ficar mais quadrada.

![image](https://cloud.githubusercontent.com/assets/5949986/17606500/76fbcf7c-5fe5-11e6-9a66-d1174865d47a.png)

3 - Arrumar o bug do ZOOM da imagem que esta abrindo o LINK e nao a Imagem maior:

![image](https://cloud.githubusercontent.com/assets/5949986/17606600/e5ab754e-5fe5-11e6-919d-067bb11b416d.png)

4 - Tirar o campo de texto do PIN

**Comment by LuwkasLima** [comment]
Matheus, achei alguns problemas...

1 - OK

2 - OK, mas....

Quando escolho 2 anos ele nao me deixa ver as fotos de outros anos:

Faça o teste:

A - Abre o PIN de São Paulo
B - Clica pra selecionar também 2012 (ou seja, pra ficar 2016 e 2012).
C - Tenta navegar as imagens de cima OU tenta clicar nas imagens de 2012 de baixo

ERRO: Não abre a imagem...
![image](https://cloud.githubusercontent.com/assets/5949986/17822006/2e3b252c-661a-11e6-9592-bee024151f28.png)

3 - OK
