### ISSUE TITLE
Icone de Pins

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/mapa-diadograffiti-theme#8]
Verifiquei e no PSD não existe icone para Pins. Estou usando o padrão, mas seria bom ter um personalizado.

**Comment by LuwkasLima** [comment]
@everaldomatias atente ao comentario do @matheusgimenez 

> se vc for fazer, faz dois tipos: um pra aglomerado de PINS (quando tem muitos pins lado a lado e ele agrupa) e outro pra pin mesmo

**Comment by LuwkasLima** [comment]
@everaldomatias faz o PIN pra nois por gentileza. So atente ao detalhes acima...

**Comment by matheusgimenez** [comment]
Feito.

Está em PRODUÇÃO

**Comment by LuwkasLima** [comment]
Aprovado!
